site/tests/editor.py, src/Lib/browser/local_storage.py, src/Lib/browser/session_storage.py, src/Lib/sys.py, src/brython_builtins.js
Adds fixes for issue #111.
- Adds sys.has_session_storage
- Refactors has_local_storage logic to handle LocalStorage being null/undefined/an exception throwing function
- Same with has_session_storage
=> Adds workarounds for localStorage and sessionStorage not being available

site/tests/test_numbers.py, src/py_int.js
Added some methods to `int` type.
It passed all the available tests and some new simple tests cases.
=> Added some methods to `int` type.

www/src/libs/_jsre.js
fixed bug on _jsre.js file.
All test passed!!
=> fixed bug, changed ] with }

README.md, www/groups.html, www/src/Lib/site-packages/header.py
Referencing IRC channel, renaming 'Social' to 'Community'
=> Documenting IRC channel

www/src/py2js.js, www/src/py_import.js
=> Brython import init

www/tests/issues.py
Also added a comment header that stands out, so as to help not to add newer tests below.
=> Moved down report that all tests have passed

www/doc/en/dev_env.md
I am a new Brython user and I had difficulty because there was a small error in the development environment setup document.  Please accept this pull request as it might save other new users trouble when they are getting started. Thanks for Brython it is an awesome tool!
=> Corrections to development environment documentation

www/src/py_builtin_functions.js, www/src/py_complex.js, www/src/py_int.js, www/src/py_range_slice.js
This PR tries to fix issue#115.
I ran the available tests and it seems the actual errors are not related with this modifications.
Please, @PierreQuentel, could you have a look to double check nothing is wrong?
Thanks.
=> fix issue #115

www/src/js_objects.js
* allow explicit `this` passing for wrapped functions
* if result is undefined, assume this being a constructor and return `this`
* save .prototype
=> fixes in JSObject function wrapping

www/src/js_objects.js, www/tests/dom.py, www/tests/dom_js_tests.js
Here's a simple test for #396 and another minor fix.
=> Another fix __getattribute__ and test for that

www/gallery/canvas_plot.html, www/src/py2js.js
Fix some bugs in a gallery example
=> Fix gallery example

www/doc/en/javascript.md
=> Fix broken JSObjects link in docs

www/src/py2js.js, www/src/py_utils.js
When `options.profile` is > 0, generated code contains instrumentation
to collect call statistics. The implementation is based on the
way line number information is added in debug mode.
Changes to `py2js.py`:
- The `$add_profile` method (like `$add_line_num`) adds instrumentation
to each line (to collect per-line statistics)
- `DefCtx` is modified to add instrumentation before each function
call and right after returning from a function call
- the `brython` function is modified to take care of the profile option
Changes to `py_utils.py`
The instrumentation is itself implemented in `py_utils.py`. It exposes
a global object `__profile__` to python programs. This object has
three methods: start, stop and pause. To start profiling, stop profiling
and pause profiling, respectively. If …
=> Start a basic implementation of profiling tools.

scripts/node_bridge.js
Changed brython script path to absolute path
=> Updated shims in node_bridge. Fixes #150

www/gallery/bokeh.html, www/gallery/gallery_en.html, www/gallery/gallery_es.html, www/gallery/gallery_fr.html
Some html housekeeping of the gallery files and addition of a new example to the gallery.
=> Added new example in the gallery for bokeh plots

www/src/py_type.js
=> fix metclass __new__ setting attributes too early

www/src/Lib/VFS_import.py
`sys` used on lines 52, 54, 83
=> import sys

www/src/py_type.js
This add support for `__init_subclass__`, which allows easier customization of class initialization.  It does not support the other half of PEP 487 (calling `__set_name__` on class attributes which support the descriptor protocol).
=> Support half of PEP 487 (__init_subclass__)

www/src/py_type.js
breaking early if one is found
=> Fix #639 by checking if metaclass is defined for current class and 

www/src/Lib/asyncio/__init__.py
Brython's `asyncio` implementation only has a single loop, so none of its methods accept a loop argument. However, some methods were copied from the CPython implementation and were not adapted to this change. This commit fixes that by removing the loop argument from all methods in `asyncio/__init__.py`.
=> Fix bug in sleep & al. passing event loop.

www/src/py_type.js
Which was (inadvertently?) undone with commit 8a34dd3fff0c59488c80cd3b1ba88501b42ddb94
=> Re-apply #645 - jonathanverner/fix-ci-broken-by-conditional-function-declaration

www/src/py_builtin_functions.js, www/src/py_dom.js
=> Fix $OpenFile implementation

www/src/py2js.js, www/src/py_import.js
This is true only in strict mode; but I think we should rename it anyway to avoid possible future breakage.
=> Package is a javascript reserved word, don't use it as variable name.

www/gallery/turtle.html, www/src/Lib/turtle.py
My first ever pull request, as a Xmas present for Brython! ;-)
I hope I did not mess up.
I implemented the changes discussed in issue #709, and updated the demo.
=> Fixing Brython issue #709

www/src/py2js.js
Fixes #740 by adding Polyfills (from MDN) for `Number.isInteger` and `Number.isSafeInteger`
See Travis-CI build test (current master + pull-request): https://travis-ci.org/mementum/brython/builds/323099404
=> Fix number issafeinteger

www/src/py2js.js
Address #768 allowing import from .. (and ... and higher if needed be)
=> Fix relative imports

README.md
=> Updated doc links

.testem.json, .travis.yml, www/tests/brython_test_utils/unittest.py
I am not sure of the root of the problem, but the assertEqual method of
unittest.TestCase was failing for some reason. Replacing it with an
equality test and a plain failureException works fine... Needs more
investigation, though.
=> fix: Fix CI

www/src/py2js.js, www/src/py_generator.js, www/tests/issues.py
This series of commits consists of some refactoring / cleanup of py2js and a reworked implementation of `yield from` which fixes Issue #765. As in my previous merge request, I'd be very happy if @PierreQuentel could take a look at the changes. Although all the tests pass, I am not very comfortable with the parser in py2js to be confident that I haven't made any stupid mistakes in my changes.
=> Fix yield from implementation

www/src/Lib/asyncio/__init__.py, www/src/Lib/asyncio/_utils.py, www/src/Lib/asyncio/coroutines.py, www/src/Lib/asyncio/events.py, www/src/Lib/asyncio/filereader.py, www/src/Lib/asyncio/fs.py, www/src/Lib/asyncio/futures.py, www/src/Lib/asyncio/objects.py, www/src/Lib/browser/timer.py, www/src/Lib/unittest/result.py, www/src/py2js.js, www/src/py_exceptions.js, www/tests/brython_test_utils/__init__.py, www/tests/brython_test_utils/unittest.py, www/tests/index.html, www/tests/issues.py, www/tests/test_aio.py, www/tests/test_classes.py
This series of commits continue my work on the `yield from` bugfix and rework asyncio to be compatible (more or less) with CPython asyncio (the implementation is based on https://www.pythonsheets.com/notes/python-asyncio.html). 
Additionally some bugfixes (mainly) in py_exceptions.js are introduced and async tests are added to the test suite.
=> Asyncio rework

www/src/py2js.js
This commit makes the compiled javascript code of functions available from python via the `__code__.co_code` attribute.
=> Populate the __code__.co_code attribute of functions with js code.

www/src/py_list.js, www/src/py_sort.js, www/tests/issues.py
=> Recover from assertion failures in the timsort code

www/tests/issues.py
Looks like you already fixed it, Pierre, so this just adds a test for it. (issue #873)
=> Add test for #873

www/src/js_objects.js, www/src/py2js.js, www/src/py_exceptions.js, www/tests/dom.py, www/tests/dom_js_tests.js, www/tests/issues.py
=> Prevent import * from replacing module's $src, plus new tests

www/src/py2js.js, www/src/py_dom.js, www/src/py_sort.js
=> Fix references to window and self for webworker compatibility

www/src/py_bytes.js, www/src/py_utils.js, www/tests/test_bytes.py
Implemented the methods listed in #705
=> (#705) Implement missing bytes methods

.testem.json
=> Reduce output from testem so that Jenkins build succeeds

www/src/Lib/browser/webworker.py, www/src/py2js.js, www/src/web_workers/worker.js
Same as #992, but without the changes to generated files.  As with before, there may be a better way of implementing these fixes, but these were the changes that were sufficient to get my program running.
=> Fix a few issues with webworkers

www/tests/console.py
Using these keys it is possible to do funny things in the console. Selecting everything on the current line for Ctrl+A seems reasonable, and page up and page down can reasonably be disabled.
=> handle CTRL-A, PGUP, PGDN keys in console.py

www/index.html
it seems that pyschool.net domain has expired
=> commented out dead link

www/src/py_bytes.js, www/src/py_string.js
I am going to close the previous pr, because I have fixed the spacing issues
=> Fixed Issue #1071

README.md, README_pt_br.md
Creat a translate of your README file to a PT-BR version
=> Portuguese README

www/src/loaders.js
Fixes https://github.com/brython-dev/brython/issues/1128.
=> Separate informational indexedDB logging from Brython output.

www/doc/pt-br/browser.md, www/doc/pt-br/create.md
Some files was translated.
To future, i pretend to use this same PR to translate the rest of files in doc/pt-br directory.
=> Translate some doc files to portuguese-br

www/doc/pt-bt/deploy.md, www/doc/pt-bt/dev_env.md
Hello, 
I translated two files, deploy.md and dev_env.md. In the future, I will translate other files to Portuguese from Brazil.
=> Translated files to Portuguese from Brazil

www/src/libs/_aio.js
Fixes #1371 
I just made the change described by @Tomaat in the issue description since it seemed like it might be helpful to turn the crank on the process.
=> Fix browser.aio.ajax headers

www/gallery/solitaire.html
After a few moves solitaire board would get messed up because of several balls having the same object id. Now solitaire is fully playable.
=> Make solitaire fully playable

www/src/py_list.js
=> Small improvment of list slice operation

scripts/node_bridge.js, small_node_app.py
Added possibility to load single module file in node environment
=> Added update for importing single module in node_bridge.js

www/speed/benchmarks/util.py
https://portingguide.readthedocs.io/en/latest/builtins.html?highlight=Reduce#moved-reduce
=> from functools import reduce for Python 3

www/src/Lib/browser/highlight.py
=> Modified browser.highlight to account for multi-line comments.

www/demo.html
I'm not sure this is correct, so I'd appreciate if someone could take a look.
=> Fix mistake in using CSS selectors

www/tutorial/pt-br/index.md
based on the tutorial written in English: https://github.com/brython-dev/brython/blob/master/www/tutorial/en/index.md
issue https://github.com/brython-dev/brython/issues/1505
=> Added tutorial translated to Brazilian Portuguese

setup/brython/__main__.py
=> Better description for --add_package

www/src/Lib/interpreter.py
=> Call the proper function when handling Ctrl+A

www/doc/en/aio.md, www/doc/fr/aio.md, www/src/Lib/browser/aio.py, www/tests/test_aio.py
=> basic Future implementation in aio module

www/tutorial/en/index.md
Just a few typos and word choices.
=> Correct typos in tutorial

Pipfile, Pipfile.lock
@PierreQuentel This is related to https://github.com/brython-dev/brython/issues/1643
=> Remove plumbum from Pipfile and update Pipfile.lock

www/src/py_import.js
Needed for custom module loader. See #1568 for more informations.
=> Expose run_js function

setup/brython/make_package.py, www/src/py_import.js
Add support for Python modules implemented in JavaScript.
=> Add js module support

www/src/Lib/turtle.py
=> fix the default behavior of dot() method

README.md, README_pt_br.md, npm/README.md
Removes spaces at the readme html examle. Changes the markdown code type from xml to html.
The same changes have been made for the document README_pt_br.md.
Also the README.md in the npm folder was updated.
=> Updating README.md files

scripts/make_ast_classes.py
=> Define ast_options before its first use on line 34

www/src/libs/math.js
=> Fix scope of a few variables in xgcd

www/src/Lib/turtle.py
Fixes #2070
Sorry, i didn't found the time to setup brython and test the changes by heart. But i think, this should fix the Problem, so the changes should probably checked a bit more carefully. Thanks for having a look.
Best regards
=> Fix rotation bug

server_modular_send_head.py
I can't reopen a pull request, dunno if it will work.
=> Use sys.executable as per schmave suggestion

www/src/loaders.js, www/src/py2js.js
The bug was introduced in commit 96401c3.
=> Fix bug that broke support for Web Workers

www/src/async.js
Please visit https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables for more information.
=> Add a condition to check if obj supports the Thenable interface

www/src/ast_to_js.js
Hi,
Tried to remove the condition in order to opti usage of `args_parser`.
Passed all unit tests, normally ready for merge.
Cordially,
=> Opti make_args_parser (ready for merge)

www/doc/en/browser.markdown.md
The word should be **Markdown**, not **Mardown**
=> Fix spelling mistake

www/src/async.js, www/src/js_objects.js
Move the logic for restoring frames from js_objects.js to async.js.
=> Fix issue #2390 and #2411

www/src/brython_builtins.js
Fix previous PR #2436.
I hope this is the right regex that time.
=> Fix URL regex

setup/brython/list_modules.py
Despite the addition of `--modules_paths`, I was still unable to use `make_modules`, as it was not scanning for stdlib dependencies of nested packages in my custom module path. With the changes in this PR, scans are successful and a produced `brython_modules.js` contains both my custom packages **and** dependencies from both `.html` and `.py` files.
Fixes #2567.
As a sidenote - is this expected that importing a package `collections` would add around 2.7MB of JS data? My modules file oscillates around 50KB, until I add a dependency on `namedtuple` from `collections`.
=> make_modules: Correctly scan sub-packages in user modules
