- src/py_string.js
This bug causes problems with expressions like:
f = "{} abcdefghijklmnopqrstuvwxyz {}".format("20", "30")
It runs REALLY slow without the  }
> Fix bug that causes exponential increase in runtime for formatting of strings with 2 or more {}

- site/doc/en/websockets.md
- site/doc/es/websockets.md
- site/doc/fr/websockets.md
- site/doc/pt/websockets.md
- src/Lib/browser/__init__.py
Hello,
I think websocket should be WebSocket, as that matches the JavaScript built-in, and it's in line with PEP naming conventions for making a constructor CamelCase.
I'm not a fan of CamelCase, but anything that matches existing standards in the browser is a good idea.
> Change websocket to WebSocket, update documentation

- src/libs/_html.js
- src/libs/_svg.js
I think the removed lines are not needed and they include wrong attributes in all browsers.
> remove unnecesary code that adds wrong attributes to DOMNode instances

- site/doc/doc_brython.css
- Add Mobile Breakpoint.
- Header menu now fits Mobile.
- Tested with Android (real devices), see Screenshot.
:iphone:
> Mobile Web

- site/tests/index.html
- site/tests/issues.py
- site/tests/test_time.py
- src/Lib/_strptime.py
- src/Lib/time.py
Some improvements have been included in the `time` module:
* Added modified version of CPython `unittests` for `time` module: Some tests related with `strptime` are not passing. `strptime` hasn't been modified in this PR.
* Improved versions of `ctime`, `gmtime`, `localtime`, `mktime`, `strftime`. This should fix issue #131
* Included a version of `sleep`. **This function should be used just for tests purposes and never in production as it blocks the browser** :dizzy_face: 
* The following will raise a `NotImplementedError`: `clock`, `clock_getres`, `clock_gettime`, `clock_settime`, `CLOCK_HIGHRES`, `CLOCK_MONOTONIC`, `CLOCK_MONOTONIC_RAW`, `CLOCK_PROCESS_CPUTIME_ID`, `CLOCK_REALTIME`, `CLOCK_THREAD_CPUTIME_ID`, `get_clock_info`, `process_time`, `tzset`.
All previous tests are passing and …
> Improvements to time.py module

- README.md
- Add Chat Room for Brython Users and Developers.
- No Logic touched, No Code changes, just 1 Line diff.
- Admins of Repo are Admins of Chat, which is Free for Open Source, like GitHub, Travis, etc and has IRC Bridge and Mobile App.
**Examples:**
- https://gitter.im/explore/tags/python
- https://gitter.im/django/django
:busts_in_silhouette:
> Add Chat Room for Brython Users and Developers

- www/src/py2js.js
I updated the `ipy_id` option in the `brython` function in order to maintain the original functionality of the option (i.e., run brython inside the IPython notebook, see https://github.com/kikocorreoso/brythonmagic for more info).
Now it takes all the scripts with their `id` included in the `ipy_id` array and add the code of all of them to be included in the  `__main__` module.
> Update ipy_id option functionality of brython function

- www/src/Lib/_socket.py
The PR makes ``socket.py`` raise ``NotImplementedError()`` on function calls not properly implemented. Doing so is explicit, direct and more transparent than just pretending that the call worked.
> socket.py: raise NotImplementedError when not implemented

- www/src/py_utils.js
Trying to import `rpyc.core.brine`, it crashes on this javascript eval. The `sc_id` should not contains `.`, only `_` IIUC. Solved [this way](http://stackoverflow.com/a/1144788/798575).
> [FIX] Replace every '.' per '_' before eval(), not 1st only

- www/src/py_type.js
This minor tweak significantly speeds up type creation when creating types with a particularly large class dict.
It causes my own .js module to load in less than one second instead of ~2.6 seconds.
> Performance improvement for new type creation

- www/tests/console.py
This fixes some annoying up-arrow behaviour in the console; pressing the up arrow to select a previously entered command would cause the history cursor not to be reset to the end.  This change makes it behave the same way as it does in the CPython console.
> Entering new line in console should set history cursor to end

- www/src/py_list.js
`count` doesn't raise a `TypeError` when more than one argument is passed.
`count` and `extend` doesn't provide the right number of arguments passed in the `TypeError` message.
> fix issue #292

- www/src/py_builtin_functions.js
- www/src/py_utils.js
to better reflect the behavior in the python3 terminal
where stdin can be replaced by a StringIO class and not thus not prompting the user for input
an example use case
import io
import sys
in_stream = io.StringIO("1\n2\n3")
sys.stdin = in_stream
while (not in_stream.closed):
print(input())
if in_stream.len==in_stream.pos:
in_stream.close()
in_stream.readline() # will throw an I/O error
sys.stdin = sys.__stdin__
input() # will prompt normally if we manage to reach it
> changed the input function

- www/src/py_list.js
- www/src/py_utils.js
- www/tests/issues.py
This PR fixes #301.
But I found some messy code doing repeated tasks.
Should this code be refactored as it seems it is repeated?
https://github.com/brython-dev/brython/blob/master/www/src/py_utils.js#L519
Here:
https://github.com/brython-dev/brython/blob/master/www/src/py_list.js#L291
And here:
https://github.com/brython-dev/brython/blob/master/www/src/py_dict.js#L402
is already defined a \_\_setitem\_\_ method.
> Fix issue #301

- server.py
- www/doc/en/dev_env.md
I added a port option to the command line in order to run `server.py` on other ports different than 8000 without the need to hard code `server.py`.
> added port option to server.py script

- www/gallery/pygame/chimp.html
Still doesn't work, site-packages/pygame was removed in 51446c31232c17e1e7471b3064bfc1d352423510; I presume it never really worked?
But at least it won't work for the right reason :-)
Before: http://brython.info/gallery/pygame/chimp.html
After:
https://rawgit.com/cben/brython/patch-1/www/gallery/pygame/chimp.html
> gallery/pygame/chimp.html: Fix brython.js 404 (but still no pygame)

- www/src/js_objects.js
Set js_func on JSObject if it wraps function
This fixes errors when JSObject-wrapped function was fed into JSConstructor
and no js_func was present.
I couldn't find any contribution guides and where to put tests, so i'll provide a simple test here to illustrate the issue:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script src="/brython.js"></script>
</head>
<body onload="brython()">
<script type="text/javascript">
window.get_constructor = function() {
return function() {
this.foo = 'hi';
};
}
</script>
<script type="text/python">
from browser import window
from javascript import JSConstructor
Foo = JSConstructor(window.get_constructor())
print(Foo().foo)
</script>
</body>
</html>
```
> fix JSObject function wrapping

- www/src/py2js.js
`loading_scripts` function was adding a nasty error when the option `ipy_id` is used in the `brython` function options. This PR should fix this issue.
> added condition to avoid a nasty error on brythonmagic

- www/doc/en/options.md
- www/doc/es/options.md
- www/src/py2js.js
Some extra info and deprecation warnings have been included in the EN and ES docs and in py2js.js to fix issue #417
It would be needed to update https://github.com/brython-dev/brython/blob/master/www/doc/fr/options.md and https://github.com/brython-dev/brython/blob/master/www/doc/pt/options.md
> added extra info about options of the brython function and tries to fix #417

- www/src/Lib/webbrowser.py
Fix to improve the behaviour of `webbrowser.open` and friends. In CPython, the following works:
````python
import webbrowser as wb
wb.open('osm.org') #http
wb.open('www.osm.org') #http
wb.open('ftp://ftp.swfwmd.state.fl.us/pub/') #ftp with protocol
wb.open('ftp.swfwmd.state.fl.us/pub/') #ftp without protocol
wb.open('gmail.com') #https
```
In Brython only the third option is working as it is included the protocol (*ftp://*) in the url.
This PR tries to fix this.
> fix some bad behaviour with webbrowser.py module

- server.py
- www/doc/en/dev_env.md
- www/doc/es/dev_env.md
Sometimes, when you are developing with brython you start the development environment from you own clone and to  have to create the static docs every time if they are not present could be tedious because is slower and you have new untracked files in your repo..
I added the option `--no-docs` to *server.py* to slightly improve the developer experience.
I also added some info on the docs in the EN and ES versions. **The FR docs should be fixed**.
> New option server.py

- www/src/py_complex.js
- www/tests/test_numbers.py
In CPython:
`print(abs(3+4j))`
returns
`5.0`
In Brython it was returning the absolute value of the real and imaginary parts.
> fix issue with absolute value of complex numbers

- www/doc/en/deploy.md
Change the URL used for deployment to an HTTPS URL.
> deployment should always be over https

- www/src/py_float.js
The `toPrecision` function prints precision number of **significant** digits instead of **number of digits after the decimal point**:
https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision)
For numbers which are close to 0 (closer than (10**-precision)) this is wrong. We should call `toFixed` instead.
This fixes Issue #486
> BUGFIX: Fix formating precision for floats close to 0 (Issue #486)

- www/src/Lib/logging/__init__.py
- www/src/Lib/logging/brython_handlers.py
- www/src/Lib/logging/handlers.py
Implement a `ConsoleHandler` (and `XMLHTTPHandler`, similar to the `HTTPHandler`) handler for the logging module which outputs the messages to the browser's debug console. Also, make `ConsoleHandler` the default `lastResort` handler.
> Implement a ConsoleHandler for the logging module

- www/src/libs/math.js
- www/src/py_float.js
- www/tests/test_math.py
Implementation of `math.inf` and `math.nan`
Implementation of [`math.isclose`](https://docs.python.org/3.5/library/math.html#math.isclose) following [CPython implementation](https://github.com/python/cpython/blob/3.5/Modules/mathmodule.c#L1993) ([,pep485](https://www.python.org/dev/peps/pep-0485), except for complex numbers);
[1]
> make math module more python3.5 compliant

- www/src/py_exceptions.js
- www/tests/issues.py
The `StopIteration` exception should have a `value` attribute. This was the intention in `py_exceptions.js` on line 364-5:
```javascript
var $exc = (BaseException+'').replace(/BaseException/g,name)
$exc = $exc.replace('//placeholder//', code)
```
Unfortunately, at least in Chromium, when converting `BaseException` to string, all comments
are discarded. The easiest fix I could think of, which is the content of this patch, is to replace
the comment with
```javascript
eval('//placeholder//');
```
which is not discarded and leads to the same result.
> BUGFIX: StopIteration exception should have a value attribute (Fixes #502).

- www/src/py_builtin_functions.js
- www/tests/issues.py
Fix Issue #506:
-- the result of the round method, if provided a second argument,
should be the same type as the first argument
Additionaly the round method should use the `__round__` method
of the object if available (the previous implementation just threw
an error).
> Fix the round method (Fixes Issue #506)

- www/tests/brython_test_utils/unittest.py
With the recent generators rewrite, CI started failing. This patch fixes the offending method. However, it is not clear to me, whether the problem is with the method or with the new implementation of generators.
> BUGFIX: Make CI tests pass again.

- www/gallery/three.html
Updated to ThreeJS #79. CanvasRenderer was moved in recent versions and it's better to use WebGLRenderer anyways, so I changed that.
> Updates ThreeJS and fixes renderer

- www/src/py_string.js
- www/tests/test_strings.py
The implementation of (l|r|)strip used regex character classes in its
implementation but did not escape special characters (like ']' or '-').
This change fixes this by not using regexes at all and using
native methods in case no chars are given. This fixes Issue #521
> Fix strip handling of bracket character (GH Issue #521).

- www/src/py2js.js
Fix for javascript error "ReferenceError: _b_ is not defined" on syntax error in python code.
This problem prevented other more useful error messages from appearing, like the cause of the syntax error.
> ReferenceError: _b_ is not defined

- www/src/Lib/_abcoll.py
- www/src/Lib/decimal.py
In this commit I would like to start a work to check if there are unused imports (e.g., [here](https://github.com/brython-dev/brython/pull/527/commits/bc194cf14325772095c2b55fb295b51070918440#diff-ea4cba5d25a8cf9530ecbfa3b1b89bb9R11)) or if there is code that is unnecessary on production on a client side (e.g., [here](https://github.com/brython-dev/brython/pull/527/commits/bcf6cd35fad8910760371346b5cb4fed1ddfaa2c#diff-977f5e6deb9b6110547b2675d7c7b1feR6481)).
If some stuff is removed it will impact positively in the performance of the import machinery and it would make some modules/packages less dependent so a production bundle can be lighter.
We should be checking CPython changes for several modules on each CPython release to check if some of our changes should be updated because there is …
> Remove some unnecesary imports

- www/src/js_objects.js
The issue doesn't have an example allowing me to reproduce the error, so
I can't say for sure that the error is fixed.
Also, I am not sure, whether the error is not in some other place:
perhaps exceptions should always have at least one argument (the
message)... So please feel free to discard the pull request if it fixes just the symptoms
and not the cause.
> BUGFIX: Don't assume exceptions have arguments (see Issue #539)

- setup/brython.py
`python -m brython --modules` didn't produce any changes in `brython_modules.js`. It was an indentation issue. I also added a print for information about the modules to be bundled.
> Fix --modules option of brython.py

- www/src/py_type.js
- www/tests/issues.py
The following code fails the second assert in Brython (but passes in
CPython).
```python
class Base:
@classmethod
def test(cls):
return cls
class Derived(Base):
def __init__(self):
pass
assert Derived.test() == Derived
d = Derived()
assert d.test() == Derived
```
The reason is that d.test() calls Base.test with the class Base as first
parameter instead of the correct Derived class.
> Fix Isseu 560: Derived classmethods passed wrong parameters.

- www/tests/qunit/unittest.js
Commit 1ad75b346e97a19 somehow broke the tests run by CI. Looking at the commit it is not quite clear to me what the exact cause was, however, after this pull request, the tests run fine again.
> Fix CI (broken by commit 1ad75b346e97a19)

- www/src/Lib/profile.py
- www/src/py2js.js
- www/src/py_utils.js
Update the profiling infrastructure to the new way of handling the frame stack. The code is now simplified by calling $profile.return from the leave_frame function.
> Update profile to new framestack

- .gitignore
After make_dist, brython.js and brython_stdlib.js are copied to the directories npm and setup/data and some git tools believe they should be added. The update to .gitignore ignores the files even if present
> Exclude from git files created in npm and setup/data after make_dist

- www/doc/en/asyncfs.md
- www/doc/en/asyncio.md
- www/doc/en/index.html
- www/doc/en/index_static.html
- www/doc/en/static_index.html
- www/src/Lib/asyncio/coroutines.py
- www/src/Lib/asyncio/fs.py
- www/src/Lib/asyncio/futures.py
The discussion on Google Groups here https://groups.google.com/d/topic/brython/HJzUFpnXNik/discussion
led me to add a simple asyncio-based implementation to access local/remote files from the browser.
For example, a simple unix-to-dos line endings converter could be written using the new `asyncio.fs` module as follows:
```python
import asyncio
import asyncio.fs as afs
@asyncio.coroutine
def todos(file_object = None):
if file_object is None:
input = yield afs.open_local()
else:
input = yield afs.open(file_object)
output = yield afs.open('processed.txt','w')
for ln in input.readlines():
output.write(ln.replace('\n','\r\n'))
output.save()
asyncio.ensure_future(todos())
```
> Asyncio fs: Implements an async open method to access local/remote files.

- www/src/py_dom.js
Putting it in action has revealed that the comparison for returning the results was reversed
> Fix behavior of select_one ... return None on no results found

- www/src/py2js.js
The `}else{` was indented to the next level, making it *really* difficult to follow the logic. Not a code breaking change.
> To follow the logic of how scripts are found in the html code

- www/src/Lib/browser/websocket.py
- www/src/js_objects.js
- also, even if not implemented, WebSocket should not accept keyword
arguments and should be a class.
> Make bind convert the Event arg to a Python obj before calling handler

- www/src/js_objects.js
- www/tests/issues.py
Javascript objects (as opposed to Python objects) can have integer
attributes, so we should not assume that attr is a string.
> Check whether attr is a string in setattr on jsobjects (Fixes #744).

- www/src/py_dict.js
- www/src/py_list.js
- www/src/py_long_int.js
- www/src/py_object.js
- www/src/py_range_slice.js
- www/src/py_set.js
- www/src/py_type.js
- www/src/py_utils.js
- www/tests/issues.py
The `__eq__` method of a class should not be used when comparing two
classes (it should only be used when comparing instances of the class).
This patch replaces instances of
```javascript
_b_.getattr(objA, '__eq__')(objB)
```
which were used to test equality of `objA`, `objB` with
```javascript
$B.rich_comp("__eq__", objA, objB)
```
which is modified to properly handle the case when `objA` and `objB` are
types.
> Fix equality comparison for types (Fixes #749)

- www/src/py2js.js
- www/tests/issues.py
The javascript code generated for
```python
for x in expr:
...
```
evaluates the expression `expr` multiple times. This commit changes the
generated code so that it evaluates the expression `expr` only once.
> fix: Evaluate iterable expression of for cycles once (Fixes #801)

- www/src/js_objects.js
- www/tests/issues.py
6888c6d67b3d5b44905a09fa427a84bef2c7b304 introduced a bug that affected Python functions that take keyword arguments if the Python function was used after being called with `pyobj2jsobj()`. The way that our code ran into this situation was by storing a Python function into the value of a dictionary that was created by using a class's `__dict__` attribute. Therefore, that's what I used for the test case. If there is a less roundabout way of having `pyobj2jsobj()` be called on a function, I'd prefer to use that for the test case since that is what is really being tested, not the implementation of `__dict__` or the special handling for `dict.$jsobj` objects.
> Fix bug in jsobjtopyobj() for kwarg objects

- www/tests/console.py
- www/tests/editor.py
Since dom changes only become visible after the script executes, there's
no reason to run `doc['console'].value += data` for every `print(data)`.
We can postpone this to just after the script executes. Also, no need to
lookup the console element by id every time, do it just once and store
it in a global variable.
This should address https://groups.google.com/forum/#!topic/brython/2vrfagT4wKg
> Buffer console output by default (improves print performance).

- www/tests/index.html
No idea why `import sys` is needed in `run`, and `run_next`, but for
some reason it is not available and calling `sys.stdout.flush` throws an
`UnboundLocalError`.
> Flush stdout in tests (fixes bug introduced in commit 62524761).

- www/src/py_builtin_functions.js
- www/tests/test_dict.py
I think that this is the correct behavior--every Python function is unique, so each should have its own hash value. I can't find any documentation to prove it, though. What do you think?
> Make functions hashable

- www/tests/console.py
- www/tests/editor.py
Unfortunately, logging still fails mysteriously. It seems that setting `record.message` on line 547 of logging/__init__.py doesn't make it available in `record.__dict__` leading to an error on line 365 of the
same file.
> fix: Implement __len__ on editor/console stderr+stdout (fixes #841)

- .travis.yml
The build for #845 failed because of a timeout error running the tests with Chromium. I checked the previous PR build in Travis and it didn't run the tests on Chromium, which made me think that some configuration changed on the Travis machine. Not sure if that is correct!
Then the build for this PR (@ c61c865) failed when running the tests with Chrome 52. It looks like we were previously running with 51. Perhaps this was also due to a change on Travis? I modified the Travis config to use the latest stable Chrome (Chrome 52 was released in 2016), and now the tests pass again.
> Travis CI: upgrade Chrome and skip Chromium

- www/src/Lib/test/test_dict.py
- www/src/Lib/traceback.py
- www/src/Lib/unittest/result.py
- www/src/py_exceptions.js
- www/tests/brython_test_utils/__init__.py
- www/tests/brython_test_utils/unittest.py
- www/tests/qunit/run_tests.html
This change causes the CPython tests in Lib/test/test_dict.py to run as part of the tests run by Qunit in Travis. Many of the tests fail, so I have added the `@unittest.skip()` decorator to them for now, with a comment that they should be investigated. The bugs I have reported over the last week or two have come from getting these tests to run, so I think there is value in having them be part of CI even though many are still skipped. 
I added an `includeInternal` flag to format_exception so that Qunit errors include the full stack trace plus the stack of any internal JS exception so that debugging is easier. I wasn't sure how to propagate this flag down into the getattr function for `exc.info`, so I added `exc.infoWithInternal`. Let me know if there is a better way to do that.
> Add Lib/test/test_dict.py to CI tests

- www/src/py2js.js
- www/tests/issues.py
4ec774359d92ceae065151b9c9280211ccc947da unintentionally (?) removed the `name` parameter from stack frames.
> Fix regression that removed function name from stack traces

- www/src/Lib/test/mapping_tests.py
Thanks to the fix for #854, `GeneralMappingTests` and `SubclassMappingTests` are now being run (in www/src/Lib/test/test_dict.py). This skips the failing ones so that CI builds succeed again. Over the next few months I hope to review the failing tests and get them passing.
> Skip failing mapping protocol tests

- www/src/Lib/traceback.py
Fixes #871
Problem: traceback.print_exc uses a fixed sys.stderr
Solution: use sys.stderr as it is when the call happens
More references: https://github.com/python/cpython/blob/bb8b1cb6af830b40f9be398d1e1bf8bdca772140/Lib/traceback.py#L97
> (#871) write traceback to sys.stderr

- CONTRIBUTING.md
correct spelling: manage,py -> manage.py
> correct spelling: manage,py -> manage.py

- www/src/libs/_jsre.js
- www/tests/issues.py
I was going to try to implement all the missing methods as mentioned in #901, but then realized that it was going to be more work than I anticipated! So I'm starting small with this PR just to add the `.sub()` method. I also implemented the `.group()` method for match objects passed to the replacement callback of `.sub()` because there was previously no way of getting the matched string from inside the replacement callback!
> Implement SRE_Pattern.sub()

- scripts/make_dist.py
This line in make_dist.py:
https://github.com/brython-dev/brython/blob/master/scripts/make_dist.py#L101
used to mangle this line and the following one in py_exceptions.js:
https://github.com/brython-dev/brython/blob/master/www/src/py_exceptions.js#L381
The generated code created exception objects with `__C__` and `__suppress_C__` properties instead of `__context__` and `__suppress_context__` properties.
What do you think of modifying the testem tests to use brython.js and brython_stdlib.js instead of the individual source files so that errors like this in the build script would be caught by the tests? It would mean that the development workflow would have to have an additional step where you run make_dist.py before running the unit tests...
> Fix minifier so that exception.__context__ is preserved

- www/src/py_bytes.js
When this function is run on Safari 10, it triggers this error: "Cannot declare a let variable twice"
> Fix py_bytes.js for Safari 10

- www/doc/en/import.md
- www/doc/es/import.md
- www/doc/fr/import.md
Currently `__init.py__` is written in the documentation (https://brython.info/static_doc/en/import.html) instead of `__init__.py`.
> Fix typo of `__init__.py` in `import` documentation

- Pipfile
- Pipfile.lock
I'm not sure if anyone is using this file since @jonathanverner's change that introduced it got partially reverted. But it's useful for me, and because of the Python library upgrade, Python 3.5 no longer works to run make_dist.py.
> Require Python 3.7 in Pipfile

- www/tests/brython_test_utils/__init__.py
- www/tests/issues.py
This was causing a failure in the qunit-based tests. There are other errors, so the Travis build still won't pass, but this is an improvement.
> Fix path to z.txt in issues.py tests

- .travis.yml
This gets the Travis build working again. I think that there is a bug in Chrome that was causing Brython's XMLHttpRequests to fail for no good reason. Switching to headless Chrome made it work again. While I was at it I cleaned up a couple other things in the build -- it now uses the latest version of Firefox instead of 59.0, and the python format check job is a little faster because it doesn't install the web browsers for that job now.
It looks like the automatic Travis build is no longer running. I found it helpful to keep track of regressions and would love to see it back again if that's possible. Let me know if I can do anything to help with it.
fyi here's the successful build running for my fork: https://travis-ci.org/cmu-cs-academy/brython/builds/539242401
> Fix Travis build by using Headless Chrome

- www/src/Lib/test/mapping_tests.py
- www/src/Lib/test/test_grammar.py
- www/tests/qunit/run_tests.html
Thanks to your fixes in #1024, CPython's test_grammar.py file can now be compiled and run in Brython. There are a few tests that fail, so I mark them as skipped so that the CI build will still pass. In case you don't have enough things on your todo list, now you can work through these :)
I removed the `@unittest.skip`'s from the dict tests that you already got working.
> Add passing test_grammar tests to CI build

- setup/list_modules.py
The fix for #1137 was little more tricky than I thought so I made a merge request.
Needs to:
- accept `Lib/site-pacakges` in `is_package`
- clean `Lib/site-pacakges/` prefix in `inspect`
- clean `Lib/site-pacakges/` prefix when building `user_modules`
On my configuration, it created a `brython_modules.js` that successfully avoids any request.
> Fixes #1137: `python -m brython --modules` does not recognize Lib/site-pacakges as packages

- .gitignore
- www/src/js_objects.js
- www/tests/test_jsobjects.py
Using `javascript.JSON.parse` produced an error, that `null` does not contain attribute `__class__`.
> Fix: `javascript.JSON.parse` crash parsing object containing null

- www/doc/en/webcomponent.md
The documentation code examples had an incorrect module path
> Fixing import of WebComponent

- www/demo.html
- www/doc/doc_brython.css
> Code blocks in docs are now in monospace
> IE is depricated, use Edge instead
> Chrome does not use "Ctrl+Shift+J" in the US, so I put a generic "right click, then click 'inspect element'" instead
> Added a notics for Safari users
> Changed "inferior or equal" to "less than or equal" because it is more widely used
> Updated site to look nicer and with better english

- www/tests/editor.html
- www/tests/editor.py
There is a problem when you share a URl with parenthesis. In some contexts the URL will not work. It is necessary to encode the parenthesis signs.
> fix problem with parenthesis in url encoding

- setup/brython/__main__.py
- setup/setup.py
When installing brython via pip of setup.py this will now add a script `brython` to the path that acts the same as `python -m brython`.
> Added entrypoint 'console_scripts' to setup.py

- .travis.yml
It seems that Travis CI last ran a year ago:
https://travis-ci.org/github/brython-dev/brython/requests
Output for this PR: https://travis-ci.com/github/cclauss/brython
> Travis CI: Modernize .travis.yml

- www/gallery/bokeh.html
Updating the bokeh.html page to use the latest versions of the libraries, bokeh-2.1.1.min.js and bokeh-api-2.1.1.min.js
> update bokeh lib to take into account changes in the API

- www/tests/qunit/run_tests.html
Prior to this change, Qunit just reported an unknown top-level error. The error is that test.test_grammar fails to parse currently.
> Improve Travis error when test_grammar or test_dict cannot be loaded

- www/tutorial/br/index.md
- www/tutorial/en/index.md
- www/tutorial/es/index.md
- www/tutorial/fr/index.md
- www/tutorial/it/index.md
If you follow the tutorial step by step, the `C` button won't work since it is defined using `TH` instead of `TD`, and no action is defined for `TH`.
> Make the draw code in tutorial consistent with the complete program

- www/src/Lib/_sre.py
https://github.com/python/cpython/blob/v3.8.5/Lib/test/test_re.py#L1885-L1887
I didn't try to fix but `SRE_Match.__init__` seems unnessessarilly set `lastindex` as `None` for negative. If there is no other bug, the only possible nagative value is `-1` and it will allow the original code run without problem.
> _sre.scanner takes keyword arguments pos, endpos in recent Python

- www/src/py_dom.js
The `height` attribute is omitted in DOMNode.set_style method.
> Bug fix: `height` attribute is omitted in style

- www/src/Lib/interpreter.py
Avoids the following bug (can be reproduced in https://brython.info/tests/console.html) :
```
Brython 3.9.1 on Netscape 5.0 (X11)
>>> print("test"); print("lipsum")
test
lipsum
>>> print("test"); print(">>>"); print("lipsum")
File <string>, line 1
); print("lipsum")
^
SyntaxError: invalid syntax (Unexpected closing bracket)
>>> 
```
Note that even with this modification there may be some cases where the computation of `currentLine` fails.
> more robust detection of current line

- www/src/Lib/interpreter.py
This allow to reproduce the behavior of `python -i my_script.py`: it executes the script, prints to console, and then launches the interactive console.
Without this modification, the output of the execution of the script (using `www/tests/editor.py` for instance) is removed as soon as the interactive console starts.
> make console cleaning optional in interpreter

- setup/brython/list_modules.py
My existing project contains lots of python files, some of them were historically encoded by non-UTF8. Those files would fail the `brython-cli --modules`. This change will output the offending files, so that I can know which file to be fixed.
> Show module path when it cannot be read

- www/src/py_string.js
- www/tests/test_strings.py
`to_chars(self)` rather than `to_chars($.self)` was causing the pickle tests to fail, and while writing the partition tests I noticed that partitions greater than 1 character long were breaking as well
> Fix bugs in string partition

- www/tests/qunit/run_tests.html
The fix for #1645 modified the traceback slightly. This PR updates the tests to match
> Fix formatting of lambda in traceback tests

- www/src/Lib/interpreter.py
Allows restoring history from a previous interpreter instance.
**Things I am no sure about:**
- we could *copy* the object (`self.history = [*history]`?) to make it safer to use internally, but I am not sure of the consequences given it's JavaScript underneath. Not sure it's worth it.
I did *not* run the test suite, but given how small the change is... I did test it in my own project that uses Brython, though.
> Accept Interpreter History as Argument

- www/tests/issues.py
With opened files, readline() seems to be working ok
but  readlines() is having some problem with linux
text files; binary mode works fine.
When readlines() is used,
files ending by '\n\n' are not having correct number of lines.
This merge request contains **only tests, not solution**.
I am not sure if merging this without solution is worth it, 
but at least it is here to remind you something needs a fix.
> added test of readline/readlines - issue #1763

- www/doc/en/keyboard_events.md
- www/doc/es/keyboard_events.md
- www/doc/fr/keyboard_events.md
The docs state you should use `ch(ev.charCode)`, but the correct function is `chr`.
Corrected for en, fr, es.
> Correct charCode conversion in docs

- www/benchmarks/index.html
This file has an extra space before the first meta tag.
> Remove extra space before viewport meta

- www/src/py_string.js
Thanks for this great project!
I had an issue using *brython*, where the following test page would not work:
```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>
<body onload="brython(1)">
<script type="text/python">
from browser import document
if "abc".startswith("b", 1):
document <= "Yes, startswith() condition is TRUE"
else:
document <= "No"
</script>
</body>
</html>
```
The text "No" would display in my browser, whereas I expected the 'startswith()' function to compare "b" to the string starting at position 1, "bc".
Patching the corresponding code in the fashion proposed here fixed the problem. (I directly patched the compiled `brython.js`, with …
> fix str.startswith() with start argument

- setup/brython/__main__.py
Use subcommands for better options delineating
```
[~]$ brython-cli 
usage: brython-cli [-h] [--version] {install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system} ...
optional arguments:
-h, --help            show this help message and exit
--version             Brython version number
subcommands:
{install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system}
Use --help with any subcommand to see more details
install (init)      Install Brython in an empty directory
update              Update Brython scripts (brython.js, brython_stdlib.js)
add_package         Add already-installed Python package to Brython project
make_package        Make a browser loadable Python package script
make_modules        Create …
```
> Rewrite cli interface

- www/src/brython_builtins.js
- www/src/builtin_modules.js
Currently, the "Javascript" button on the website is broken:
This PR fixes that, though I'm not sure it's the cleanest fix. Setting the filename of the source object causes Brython to correctly generate a scope object.
> Fix Python to Javascript conversion functions

- www/src/builtin_modules.js
- www/tests/brython_test_utils/__init__.py
I looked into why the test_jsobjects.py tests are failing on master. I couldn't figure it out :) But I did make these two little changes that were causing spurious errors at least. 
Looks like `javascript.import_js('js_test.js')` is failing in test_jsobjects.py, for what it's worth.
> Add $B.UndefinedType.__str__

- www/src/py2js.js
This fixes the first bug in #2008
> Add range info for positional argument syntax error

- www/src/Lib/external_import.py
`www/src/Lib/external_import.py` uses `sys` on lines 53, 55, and 84 but it is never imported or defined.
> Fix undefined name 'sys' in www/src/Lib/external_import.py

- www/src/Lib/browser/ui.py
`rows` are appended to and returned to the caller but they are never defined leading to an undefined name.
> Fix undefine name 'rows' in www/src/Lib/browser/ui.py

- .travis.yml
`scripts/make_ast_classes.py` was fixed in #2004 so it can be removed from flake8's excluded list.
> Remove make_ast_classes.py from flake8 excludes

- www/src/brython_builtins.js
NW.js (https://nwjs.io/) was based on Node, but has no module object, but like browser in other aspects
> Detect NW.js environment as browser-like (due to lack of module object)

- Pipfile
- Pipfile.lock
- www/brython.css
I have updated the pipfile python version to the latest i.e python3.11 as Brython's latest version is 3.11 and it was not passing the version check for make_dist.py in the src directory.
The second change was  a small correction in the CSS file
> Updating Version in Pipfile and correction bryton.css file

- www/src/ast_to_js.js
manually passed test case provided in issue #2148 (successfully calls the right `__anext__` method), and the entire test suite passes.
> fixed async-for bug #2148

- .travis.yml
- scripts/make_dist.py
- www/src/py_float.js
- www/tests/test_numbers.py
* make_dist.py was failing on Travis but not causing the build to fail, so I added a non-zero exit code when it is run with the wrong version of Python
* int(-3.5) used to return -4 instead of -3, so I fixed that.
> Fix float->int conversion; fix make_dist on Travis

- www/src/ast_to_js.js
- www/src/py_exceptions.js
Following up on e01daaf799d19c55b956db06742ecf6f283c1f57, this changes a few more calls to NameError.$factory to use $B.name_error. I also removed an unused argument from $B.name_error.
It seems like resolve_global isn't used by the tests, maybe because they use exec (?), so I don't see how to add an automated test for this.
> Convert remaining NameError.$factory to $B.name_error

- www/src/js_objects.js
On Brython <=> JS object conversions :
- Some optimizations
- Some bug fixes
Issue #2249 not fixed.
I think we really need to implement the prototype substitution, without it Brython <=> JS object conversions is chaotic.
Conversions of Arrays/Tuple/List is dangerous. Arrays should be handled as a List and shouldn't be copied (need prototype substitution for that). Tuple should be a `Object.frozen()` array.
> Tried to fix issue 2249

- server.py
Fix #1913.
Usage :
````
python3 server.py # listen on 127.0.0.1 only (secure)
python3 server.py --ip 0.0.0.0 # listen on all interfaces (old behavior)
python3 server.py --ip 192.168.1.1 # listen on a given IP address.
````
> Fix issue #1913 (server open to outside world by default) by adding new --ip option to server.py

- .travis.yml
One of your recent commits caused the Travis CI build process to fail. The current release of Ubuntu LTS only supports Python 3.10.
> Add the deadsnakes repository for supporting CPython 3.12 in Travis

- www/brython.css
- www/doc/doc_brython.css
- www/tests/console.css
I fix some CSS errors and set the `<pre>` HTML tag style to monospaced font, not default browser font (like Times New Roman serif font in [Brython interactive console at Brython website](https://brython.info/tests/console.html))
> Fix errors and set `pre` HTML tag style to monospace, not default browser font (Times New Roman serif font)

- www/src/js_objects.js
Remove the Thenable interface check from js_objects.js since it's already handled in async.js
> Fix issue #2399

- www/src/brython_builtins.js
The regular expression from the `strip_host` function may cause errors when running Brython in embedded browsers.
For example, here is an error that I get with a [tauri](https://tauri.app) app:
```
Error: not a url: tauri://localhost#__main__1093904193440517
(anonymous function) (brython.js:49)
run_scripts (brython.js:944:139)
injectPythonScript (brython.js:869)
(anonymous function) (brython.js:883:154)
```
This pull request aim to fix that.
I added a question mark because sometimes the URL is just `tauri://localhost`, which also makes the function throw an error.
> Soften URL regex

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Brython Guru](https://gurubase.io/g/brython) to Gurubase. Brython Guru uses the data from this repo and data from the [docs](https://www.brython.info/static_doc/3.13/en/intro.html) to answer questions by leveraging the LLM.
In this PR, I showcased the "Brython Guru", which highlights that Brython now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …
> Introducing Brython Guru on Gurubase.io

- www/src/ast_to_js.js
`ast_dump()` in ast_to_js.js uses classes like `ast.Constant`, but `ast` is not defined in the file. The references need to be changed to `$B.ast.Constant`.
Problem was discovered while working on issue #2520.
> Fix unqualified references to $B.ast in ast_dump()

- setup/brython/__main__.py
Very simple oversight I mentioned as part of a different issue in https://github.com/brython-dev/brython/issues/2567#issuecomment-2835174777.
With this PR, `make_package` respects the passed `--src-dir` directory. The default `--output-path` remains unchanged and is still relative to the source directory - personally I think it should be relative to the **current** directory, as then that'd accommodate for directory structure like this:
```
assets\
brython\
my_modules.py
js\
my_modules.brython.js
```
without having to resort to a strange relative output path in the form of `..\js\my_modules.brython.js`.
I am not going to make this call on my own though. @PierreQuentel if you think this behaviour makes more sense than the current one, I'll update the PR modifying `--output-path` with its …
> Fix `make_package` ignoring `--src-dir`

- www/src/brython_builtins.js
In the documentation:
```JavaScript
var src = "import some_module"
__BRYTHON__.runPythonSource(src, {pythonpath: 'my_modules', debug: 2})
```
has now a clean API:
```JavaScript
__BRYTHON__.importPythonModule(some_module, {pythonpath: 'my_modules', debug: 2})
```
> Add JS convenient function importPythonModule

- www/console.html
Right now, opening console page shows two errors in DevTools:
```
Uncaught TypeError: can't access property "__getattribute__", $B.function is undefined
<anonymous> https://brython.info/src/py_builtin_functions.js:3403
<anonymous> https://brython.info/src/py_builtin_functions.js:3463
Uncaught TypeError: can't access property "__getattribute__", $B.function is undefined
<anonymous> https://brython.info/src/builtin_modules.js:1295
<anonymous> https://brython.info/src/builtin_modules.js:1507
```
which seem to break console functionality.
> Fix console page
